@web_api_HostAddress = https://localhost:7126
@web_api_HostAddress = http://localhost:5039

GET {{web_api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{web-api_HostAddress}}/api/superhero

###
