@web_api_HostAddress = https://localhost:7126

POST {{web_api_HostAddress}}/api/superhero
Content-Type: application/json

{
  //SuperHero
}

###

GET {{web_api_HostAddress}}/api/superhero

###

GET {{web_api_HostAddress}}/api/superhero/0

###

GET {{web_api_HostAddress}}/weatherforecast

###
